import type { ReactorModeDefinition, ReactorModeId } from "@/types/reactor";

export const REACTOR_MODES: ReactorModeDefinition[] = [
  {
    id: "mark-i",
    name: "Mark I",
    shortName: "MK I",
    primaryColor: { r: 210, g: 250, b: 255 },
    secondaryColor: { r: 97, g: 232, b: 255 },
    glow: 0.72,
    noise: 0.34,
    rotationSpeed: 0.32,
    surgeFrequency: 0.12,
    breathingSpeed: 0.48,
    particleDensity: 0.42,
    bloom: 0.66,
    description: "Original palladium core behavior with slow containment rotation and restrained plasma bloom.",
  },
  {
    id: "mark-ii",
    name: "Mark II",
    shortName: "MK II",
    primaryColor: { r: 140, g: 247, b: 255 },
    secondaryColor: { r: 255, g: 255, b: 255 },
    glow: 0.84,
    noise: 0.44,
    rotationSpeed: 0.48,
    surgeFrequency: 0.18,
    breathingSpeed: 0.58,
    particleDensity: 0.55,
    bloom: 0.78,
    description: "Tighter field lines, brighter edge ionization, and more active rotational turbulence.",
  },
  {
    id: "mark-iii",
    name: "Mark III",
    shortName: "MK III",
    primaryColor: { r: 97, g: 232, b: 255 },
    secondaryColor: { r: 221, g: 254, b: 255 },
    glow: 0.94,
    noise: 0.56,
    rotationSpeed: 0.64,
    surgeFrequency: 0.24,
    breathingSpeed: 0.7,
    particleDensity: 0.7,
    bloom: 0.88,
    description: "Balanced cinematic reactor profile with active magnetic current and bright white-blue core bias.",
  },
  {
    id: "avengers",
    name: "Avengers",
    shortName: "AVG",
    primaryColor: { r: 255, g: 255, b: 255 },
    secondaryColor: { r: 74, g: 255, b: 180 },
    glow: 1,
    noise: 0.5,
    rotationSpeed: 0.78,
    surgeFrequency: 0.2,
    breathingSpeed: 0.54,
    particleDensity: 0.74,
    bloom: 0.98,
    description: "High-output clean white plasma with emerald signal harmonics and strong field stability.",
  },
  {
    id: "nano",
    name: "Nano",
    shortName: "NANO",
    primaryColor: { r: 145, g: 102, b: 255 },
    secondaryColor: { r: 97, g: 232, b: 255 },
    glow: 0.9,
    noise: 0.72,
    rotationSpeed: 0.92,
    surgeFrequency: 0.32,
    breathingSpeed: 0.82,
    particleDensity: 0.86,
    bloom: 0.92,
    description: "Fast nanoscale lattice modulation with violet phase shift and aggressive edge shimmer.",
  },
  {
    id: "experimental",
    name: "Experimental",
    shortName: "XPR",
    primaryColor: { r: 255, g: 77, b: 90 },
    secondaryColor: { r: 255, g: 209, b: 102 },
    glow: 0.98,
    noise: 0.9,
    rotationSpeed: 1.12,
    surgeFrequency: 0.44,
    breathingSpeed: 0.96,
    particleDensity: 1,
    bloom: 1,
    description: "Unstable field research profile with thermal accents, fast current drift, and high surge activity.",
  },
];

export const REACTOR_MODE_MAP = REACTOR_MODES.reduce(
  (modes, mode) => ({
    ...modes,
    [mode.id]: mode,
  }),
  {} as Record<ReactorModeId, ReactorModeDefinition>,
);

export const getReactorMode = (id: ReactorModeId): ReactorModeDefinition => REACTOR_MODE_MAP[id];
